### ISSUE TITLE
Stats Resetting at 4pm local time

### ISSUE THREAD

**Issue by jmunowitch** [KoljaWindeler/energy_calc#2]
I stubbled upon the repo as the solution to my HA energy problems! I am excited because it solves a significant challenge to using the HA energy dashboard

Once setting this up, the energy dashboard worked great! Until I noticed the data seems to be resetting at 4pm local time (America/Los_Angeles):
<img width="1241" alt="image" src="https://user-images.githubusercontent.com/1542229/200735829-2c64a159-2a46-4186-b6f2-58c0cd5abf5b.png">

I am a bit baffled why this is happening. My uneducated guess is timezones... but I have no real evidence of this. 
```
template:
  - sensor:
      - name: "Grid To Home"
        state: "{{state_attr('sensor.energy_calc', 'Grid_to_home_[kWh]')}}"
        device_class: energy
        state_class: total 
        unit_of_measurement: "kWh"
  - sensor:
      - name: "Solar To Grid"
        state: "{{state_attr('sensor.energy_calc', 'Solar_to_grid_[kWh]')}}"
        device_class: energy
        state_class: total_increasing 
        unit_of_measurement: "kWh"
```

in config_entries:
```
      {
        "entry_id": "55773e0064dd5541edd8ab10811111bc",
        "version": 1,
        "domain": "energy_calc",
        "title": "energy_calc",
        "data": {
          "name": "Home Power",
          "icon": "mdi:weather-sunny",
          "gen_id": "sensor.solaredge_current_power",
          "net_id": "sensor.home_123_1min"
        },
```

Solar is coming in through the [solaredge](https://www.home-assistant.io/integrations/solaredge/) integration and the power is coming from the [ha-emporia-vue](https://github.com/magico13/ha-emporia-vue) integration.

Any help in figuring out why the stats are resetting at 4pm local time would be great!
